### PR TITLE
world added

### PR DESCRIPTION
**Pull request by dmakaroff-rw**
This change is [Reviewable](https://reviewable.io/reviews/dmakaroff-rw/foobar/3)

### CODE REVIEW

**Comment by dmakaroff-rw** [comment]
foo bar

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[hello.txt, line 2 at r1](https://reviewable.io:443/reviews/dmakaroff-rw/foobar/3#-Kz3KDCTNFyocZ43g54M:-Kz3KDCTNFyocZ43g54N:b-intqry) ([raw file](https://github.com/dmakaroff-rw/foobar/blob/014b19f35861fbba09d4193b1accd2466ad53c3d/hello.txt#L2)):*
> ```
> hello
> world
> ```

world?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dmakaroff-rw/foobar/3#-:-Kz3K9Aaw8l-ql8S6G_P:bo8zuhg)*

**Comment by dmakaroff-rw** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[hello.txt, line 2 at r1](https://reviewable.io:443/reviews/dmakaroff-rw/foobar/3#-Kz3KDCTNFyocZ43g54M:-Kz3KeTw5gy7O2gD09Tx:b-896fix) ([raw file](https://github.com/dmakaroff-rw/foobar/blob/014b19f35861fbba09d4193b1accd2466ad53c3d/hello.txt#L2)):*
<details><summary><i>Previously, dmakaroff-rw (Dmitry Makarov) wrote…</i></summary><blockquote>

world?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dmakaroff-rw/foobar/3)*

**Comment by llindqvi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[hello.txt, line 2 at r1](https://reviewable.io:443/reviews/dmakaroff-rw/foobar/3#-Kz3NO1MGmP452uwurba:-Kz3NO1NdnFfxWNEpqzT:b-pavfkb) ([raw file](https://github.com/dmakaroff-rw/foobar/blob/6915c38180627989e818328a8f0504f721ba2706/hello.txt#L2)):*
> ```
> hello
> world
> ```

more ambition: world-> universe

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dmakaroff-rw/foobar/3)*

**Comment by dmakaroff-rw** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[hello.txt, line 2 at r1](https://reviewable.io:443/reviews/dmakaroff-rw/foobar/3#-Kz3NO1MGmP452uwurba:-Kz3Ns0pjJ91FDY89NZA:b-896fix) ([raw file](https://github.com/dmakaroff-rw/foobar/blob/6915c38180627989e818328a8f0504f721ba2706/hello.txt#L2)):*
<details><summary><i>Previously, llindqvi (Lasse Lindqvist) wrote…</i></summary><blockquote>

more ambition: world-> universe
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dmakaroff-rw/foobar/3)*

**Comment by llindqvi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dmakaroff-rw/foobar/3)*

**Comment by llindqvi** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dmakaroff-rw/foobar/3)*

**Comment by llindqvi** [comment]
you need to do something more

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dmakaroff-rw/foobar/3#-:-Kz3OtbNEIn8hT2afvYE:bjhh29b)*

**Comment by llindqvi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[hello.txt, line 4 at r2](https://reviewable.io:443/reviews/dmakaroff-rw/foobar/3#-Kz3PTITnaNgZzrE8LkA:-Kz3PTITnaNgZzrE8LkB:b-fddm6m) ([raw file](https://github.com/dmakaroff-rw/foobar/blob/3571ec168bc14670f0fbeb3e9f2c1b3dded279fb/hello.txt#L4)):*
> ```
> world
> some change
> one more
> ```

let's do something more

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dmakaroff-rw/foobar/3)*

**Comment by dmakaroff-rw** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[hello.txt, line 4 at r2](https://reviewable.io:443/reviews/dmakaroff-rw/foobar/3#-Kz3PTITnaNgZzrE8LkA:-Kz3Rl7ZluJ4BMg5UF6x:b-896fix) ([raw file](https://github.com/dmakaroff-rw/foobar/blob/3571ec168bc14670f0fbeb3e9f2c1b3dded279fb/hello.txt#L4)):*
<details><summary><i>Previously, llindqvi (Lasse Lindqvist) wrote…</i></summary><blockquote>

let's do something more
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dmakaroff-rw/foobar/3)*

**Comment by vmalkov-rw** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[hello.txt, line 1 at r2](https://reviewable.io:443/reviews/dmakaroff-rw/foobar/3#-Kz3X0DVAtxJ-jueEZ3u:-Kz3X0DVAtxJ-jueEZ3v:b-vvo09y) ([raw file](https://github.com/dmakaroff-rw/foobar/blob/3571ec168bc14670f0fbeb3e9f2c1b3dded279fb/hello.txt#L1)):*
> ```
> hello
> ```

Should start with capital.

---

*[hello.txt, line 3 at r2](https://reviewable.io:443/reviews/dmakaroff-rw/foobar/3#-Kz3XDXhP51jOx2jsjjL:-Kz3XDXhP51jOx2jsjjM:b47cjxo) ([raw file](https://github.com/dmakaroff-rw/foobar/blob/3571ec168bc14670f0fbeb3e9f2c1b3dded279fb/hello.txt#L3)):*
> ```
> hello
> world
> some change
> ```

Also please add another.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dmakaroff-rw/foobar/3)*

**Review by llindqvi — APPROVED** [review]

**Pull request closed without merging**
